/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Users.Admin;
import Business.Users.Customer;
import Business.Users.Supplier;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author TechieTribe (ravindran.n@husky.neu.edu , varmavimal.v@husky.neu.edu, gubballi.s@husky.neu.edu)
 */
public class AdminCreateScreen extends javax.swing.JPanel {

    /**
     * Creates new form AdminScreen
     */
    private JPanel panelRight;
    private Admin admin;
    public AdminCreateScreen(JPanel panelRight, Admin admin) {
        initComponents();
        this.panelRight = panelRight;
        this.admin = admin;
    }
    
    private boolean passwordPatternCorrect()
    {
        Pattern p = Pattern.compile("^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,}$");
        Matcher m = p.matcher(txtPword.getText());
        boolean b = m.matches();
        //boolean b = m.find();
        if(b==true)
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnCreate = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        UsernameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioCustomer = new javax.swing.JRadioButton();
        radioSupplier = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        displayCorSTxt = new javax.swing.JTextField();
        txtPword = new javax.swing.JPasswordField();
        txtRePword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 560, 173, -1));
        add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 131, 173, -1));

        UsernameLabel.setText("username:");
        add(UsernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 134, -1, -1));

        jLabel2.setText("password:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 192, -1, -1));

        jLabel3.setText("re-enter password :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 326, -1, -1));

        buttonGroup1.add(radioCustomer);
        radioCustomer.setText("Customer");
        radioCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCustomerActionPerformed(evt);
            }
        });
        add(radioCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 78, -1, -1));

        buttonGroup1.add(radioSupplier);
        radioSupplier.setText("Supplier");
        radioSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSupplierActionPerformed(evt);
            }
        });
        add(radioSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 78, -1, -1));

        btnBack.setText("< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 13, -1, -1));

        jLabel4.setText("I am a :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 82, -1, -1));

        jLabel5.setText("Creating A New");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 378, -1, -1));

        displayCorSTxt.setEditable(false);
        displayCorSTxt.setEnabled(false);
        add(displayCorSTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 375, 173, -1));
        add(txtPword, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 189, 173, -1));
        add(txtRePword, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 323, 173, -1));

        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Password must have: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 300, -1, -1));

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Minimum 8 characters.");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 326, -1, -1));

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("At least one Uppercase.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 352, -1, -1));

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("At least one LowerCase.");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 378, -1, -1));

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("At least one Number.");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 401, -1, -1));

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("At least one Special Character.");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 424, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // Binding code for creating a new user.
        //try
        //{   
        if(txtUser.getText().isEmpty() && txtPword.getText().isEmpty() && txtRePword.getText().isEmpty())
            {
                //throw new RuntimeException();
                JOptionPane.showMessageDialog(null, "Enter inputs for all fields");
                return;
            }
        else 
        {
            if (radioCustomer.isSelected())
            {
                
                if(passwordPatternCorrect())
                {
                    Customer cust = admin.addCustomer();
                    cust.setUserName(txtUser.getText());
                    cust.setPassword(txtPword.getText());
                    JOptionPane.showMessageDialog(null, "New Customer Account Created!");
                }
                else
                {
                    
                    JOptionPane.showMessageDialog(null, "Password does not comply with the requirements!");
                    return;
                }


                txtUser.setText("");
                txtPword.setText("");
                txtRePword.setText("");
                displayCorSTxt.setText("");
            }
            else
            {
                
                //if(admin.searchUsername(txtUser.getText()))
                //{
                    if(passwordPatternCorrect())
                    {
                        Supplier supplier = admin.addSupplier();
                        supplier.setUserName(txtUser.getText());
                        supplier.setPassword(txtPword.getText());

                        JOptionPane.showMessageDialog(null, "New Supplier Account Created!");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Password does not comply with the requirements!");
                        return;
                    }


                    txtUser.setText("");
                    txtPword.setText("");
                    txtRePword.setText("");
                    displayCorSTxt.setText("");
            }
               /* else
                {
                    JOptionPane.showMessageDialog(null, "Username already exists!");
                    return;
                
                }*/
                
            
        }
        
//        catch(RuntimeException e)
//        {
//           JOptionPane.showMessageDialog(null, "Enter inputs for all fields");
//           return;
      
    }//GEN-LAST:event_btnCreateActionPerformed

    private void radioCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCustomerActionPerformed
        // Setting value to the text field
        displayCorSTxt.setText(radioCustomer.getText());
    }//GEN-LAST:event_radioCustomerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // Mve back to previous page.
        Component[] components= panelRight.getComponents();
        for (Component c: components)
        {
            
            if(c instanceof AdminMainScreen)
            {
                AdminMainScreen panel=(AdminMainScreen)c;
                panel.populateCustomer();
                panel.populate();
            }
        }
        
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.remove(this);
        layout.previous(panelRight);
    }//GEN-LAST:event_btnBackActionPerformed

    private void radioSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSupplierActionPerformed
        // Setting value to the text field
        displayCorSTxt.setText(radioSupplier.getText());
    }//GEN-LAST:event_radioSupplierActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField displayCorSTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton radioCustomer;
    private javax.swing.JRadioButton radioSupplier;
    private javax.swing.JPasswordField txtPword;
    private javax.swing.JPasswordField txtRePword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
