/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Abstract.User;
import Business.Users.Admin;
import Business.Users.Customer;
import Business.Users.Supplier;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author TechieTribe (ravindran.n@husky.neu.edu , varmavimal.v@husky.neu.edu, gubballi.s@husky.neu.edu)
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    List<User> list;
    JPanel panelRight;
    private User user;
    private Admin adminUser;
    public LoginScreen(JPanel panelRight, List<User> list, Admin adminUser) {
        initComponents();
        this.list = list;
        this.panelRight = panelRight;
        this.adminUser = adminUser;
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmit = new javax.swing.JButton();
        txtTitle = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        btnSubmit.setText("Login");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        comboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addComponent(comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(txtTitle)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtTitle)
                .addGap(30, 30, 30)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        txtTitle.getAccessibleContext().setAccessibleName("for (Object obj : adminUser.getCustDir().getCustomerList()){\n            //Customer c = (Customer) obj;\n            user = (User) comboBox.getSelectedItem();\n            if(user instanceof Customer){\n                txtTitle.setText(\"Customer Login Screen\"); \n            }\n            \n        }\n  \n        for (Object obj : adminUser.getSuppDir().getSupplierList()){\n            user = (User) comboBox.getSelectedItem();\n            if(user instanceof Supplier){\n                txtTitle.setText(\"Supplier Login Screen\"); \n            }\n        }");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
            if(!adminUser.verify(txtPassword.getText()) || !adminUser.verifySupplier(txtPassword.getText())){
                SuccessScreen successScreen = new SuccessScreen(user);
                panelRight.add("SuccessScreen",successScreen);
                CardLayout layout = (CardLayout)panelRight.getLayout();
                layout.next(panelRight);
            }
            else {
                JOptionPane.showMessageDialog(null, "Please eneter correct password");
                return;
            }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
       user = (User) comboBox.getSelectedItem();
            if(user instanceof Supplier){
                txtTitle.setText("Supplier Login Screen");  
        }
            else{
                txtTitle.setText("Customer Login Screen");
            }
            
    }//GEN-LAST:event_comboBoxActionPerformed

    
    private void initialize(){
        //text should either be "Supplier Login Screen" OR "Customer Login Screen"
        //Based on the selection
        comboBox.removeAllItems();
        for(Object obj : adminUser.getCustDir().getCustomerList() ){
            user = (User) obj;
            comboBox.addItem(user);
        }
        
        for(Object obj : adminUser.getSuppDir().getSupplierList()){
            user = (User) obj;
            comboBox.addItem(user);
        }
        
        /*for (Object obj : adminUser.getCustDir().getCustomerList()){
            Customer c = (Customer) obj;
            //user = (User) comboBox.getSelectedItem();
            if(comboBox.getSelectedItem().equals(c.getUserName())){
                txtTitle.setText("Customer Login Screen"); 
            }
            else{
                txtTitle.setText("Supplier Login Screen");
            }
            
        }
  
        /*for (Object obj : adminUser.getSuppDir().getSupplierList()){
            user = (User) comboBox.getSelectedItem();
            if(user instanceof Supplier){
                txtTitle.setText("Supplier Login Screen"); 
            }
        }*/
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
